#s line to define a global platform for your project
platform :ios, '8.0'

target 'SampleApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
  pod 'PianoComposer', '~>1.0.0-alpha3'
 
end

